
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPT = 10;
  public static final int CONCATENACION = 15;
  public static final int RESALTOLINEA = 7;
  public static final int CERRADURAINTER = 19;
  public static final int DECIMAL = 22;
  public static final int HASTA = 6;
  public static final int REVALUAR = 24;
  public static final int TODOS = 2;
  public static final int UMENOS = 23;
  public static final int ASIGN = 12;
  public static final int CERRADURAMAS = 18;
  public static final int RECOMILLASIMPLE = 8;
  public static final int LLAVEIZQ = 13;
  public static final int SEPARADOR = 20;
  public static final int LLAVEDER = 14;
  public static final int EOF = 0;
  public static final int KLEEN = 17;
  public static final int RECOMILLASDOBLES = 9;
  public static final int SIMBOLO = 5;
  public static final int CONJ = 3;
  public static final int DISYUNCION = 16;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 4;
  public static final int ENTERO = 21;
  public static final int PTCOMA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TODOS",
  "CONJ",
  "IDENTIFICADOR",
  "SIMBOLO",
  "HASTA",
  "RESALTOLINEA",
  "RECOMILLASIMPLE",
  "RECOMILLASDOBLES",
  "DOSPT",
  "PTCOMA",
  "ASIGN",
  "LLAVEIZQ",
  "LLAVEDER",
  "CONCATENACION",
  "DISYUNCION",
  "KLEEN",
  "CERRADURAMAS",
  "CERRADURAINTER",
  "SEPARADOR",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "REVALUAR"
  };
}

